services:
  node:
    image: "node:latest"
    user: "node"
    working_dir: /home/app
    environment:
      - NPM_CONFIG_LOGLEVEL=${LOG_LEVEL}
    volumes:
      - ./:/home/app
    ports:
      - ${PORT}:${PORT}
    command: "npm run start:dev"
    env_file:
      - .env
